#draw a line for the target CD and thickness
draw_wavelength1=1;
draw_wavelength2=1;
target_cd_value = -25*nm; # no.3
cd_value=3;
target_thick_value = -2*nm; # no.8
thick=8;
if(draw_wavelength1==1){
plotxy(DC_length_ratio,coupling_efficiency(3,:,8),
"DC_length_ratio","Coupling efficiency","wl="+num2str(round(wavelength1*1e9))+"nm"+"_CD shift"+num2str(round(parameter_cd(cd_value)*1e9))+"nm_thickness"+num2str(round(parameter_thick(thick)*1e9))+"nm");
}
if(draw_wavelength2==1){
plotxy(DC_length_ratio,(1-leakage(3,:,8)),
"DC_length_ratio","Coupling efficiency","wl="+num2str(round(wavelength2*1e9))+"nm"+"_CD shift"+num2str(round(parameter_cd(cd_value)*1e9))+"nm_thickness"+num2str(round(parameter_thick(thick)*1e9))+"nm");
}
